### PR TITLE
fix step result judgment

### PR DESCRIPTION
**Pull request by EnnawYang**
fix: https://github.com/P3TERX/Actions-OpenWrt/commit/8330db576b78d8e6e7331138fbb7b17e3941e24c#commitcomment-53657226  

sorry , my bad

### CODE REVIEW

**Comment by 1-1-2** [comment]
没得问题了，两位辛苦~

**Comment by admin6750217** [comment]
0s
Run echo "::set-output name=release_tag::$(date +"%Y.%m.%d-%H%M")"
  echo "::set-output name=release_tag::$(date +"%Y.%m.%d-%H%M")"
  touch release.txt
  [ $UPLOAD_COWTRANSFER = true ] && echo "🔗 [Cowtransfer]()" >> release.txt
  [ $UPLOAD_WETRANSFER = true ] && echo "🔗 [WeTransfer]()" >> release.txt
  shell: /usr/bin/bash -e {0}
  env:
    REPO_URL: https://github.com/coolsnowwolf/lede
    REPO_BRANCH: master
    FEEDS_CONF: feeds.conf.default
    CONFIG_FILE: .config
    DIY_P1_SH: diy-part1.sh
    DIY_P2_SH: diy-part2.sh
    UPLOAD_BIN_DIR: true
    UPLOAD_FIRMWARE: true
    UPLOAD_COWTRANSFER: false
    UPLOAD_WETRANSFER: false
    UPLOAD_RELEASE: true
    TZ: Asia/Shanghai
    DEVICE_NAME: _d-team_newifi-d2
    FILE_DATE: _202107201218
    FIRMWARE: /home/runner/work/newifi_d2/newifi_d2/openwrt/bin/targets/ramips/mt7621
Error: Process completed with exit code 1.

**Comment by admin6750217** [comment]
不行了，更新后，再次云编译直接失败。之前的一直很好用！
这是现在的

0s
Run echo "::set-output name=release_tag::$(date +"%Y.%m.%d-%H%M")"
  echo "::set-output name=release_tag::$(date +"%Y.%m.%d-%H%M")"
  touch release.txt
  [ $UPLOAD_COWTRANSFER = true ] && echo "🔗 [Cowtransfer]()" >> release.txt
  [ $UPLOAD_WETRANSFER = true ] && echo "🔗 [WeTransfer]()" >> release.txt
  shell: /usr/bin/bash -e {0}
  env:
    REPO_URL: https://github.com/coolsnowwolf/lede
    REPO_BRANCH: master
    FEEDS_CONF: feeds.conf.default
    CONFIG_FILE: .config
    DIY_P1_SH: diy-part1.sh
    DIY_P2_SH: diy-part2.sh
    UPLOAD_BIN_DIR: true
    UPLOAD_FIRMWARE: true
    UPLOAD_COWTRANSFER: false
    UPLOAD_WETRANSFER: false
    UPLOAD_RELEASE: true
    TZ: Asia/Shanghai
    DEVICE_NAME: _d-team_newifi-d2
    FILE_DATE: _202107201218
    FIRMWARE: /home/runner/work/newifi_d2/newifi_d2/openwrt/bin/targets/ramips/mt7621
Error: Process completed with exit code 1.

**Comment by 1-1-2** [comment]
> 不行了，更新后，再次云编译直接失败。之前的一直很好用！
> 这是现在的
> 
> 0s
> Run echo "::set-output name=release_tag::$(date +"%Y.%m.%d-%H%M")"
> echo "::set-output name=release_tag::$(date +"%Y.%m.%d-%H%M")"
> touch release.txt
> [ $UPLOAD_COWTRANSFER = true ] && echo "🔗 Cowtransfer" >> release.txt
> [ $UPLOAD_WETRANSFER = true ] && echo "🔗 WeTransfer" >> release.txt
> shell: /usr/bin/bash -e {0}
> env:
> REPO_URL: https://github.com/coolsnowwolf/lede
> REPO_BRANCH: master
> FEEDS_CONF: feeds.conf.default
> CONFIG_FILE: .config
> DIY_P1_SH: diy-part1.sh
> DIY_P2_SH: diy-part2.sh
> UPLOAD_BIN_DIR: true
> UPLOAD_FIRMWARE: true
> UPLOAD_COWTRANSFER: false
> UPLOAD_WETRANSFER: false
> UPLOAD_RELEASE: true
> TZ: Asia/Shanghai
> DEVICE_NAME: _d-team_newifi-d2
> FILE_DATE: _202107201218
> FIRMWARE: /home/runner/work/newifi_d2/newifi_d2/openwrt/bin/targets/ramips/mt7621
> Error: Process completed with exit code 1.

这个是因为 [ $UPLOAD_WETRANSFER = true ] 返回了 false，也就是1，导致 step failed... 挺奇葩的，你在这一步的最后加个echo把返回值盖过去就可以了

```yml
echo "::set-output name=release_tag::$(date +"%Y.%m.%d-%H%M")"
touch release.txt
[ $UPLOAD_COWTRANSFER = true ] && echo "🔗 Cowtransfer" >> release.txt
[ $UPLOAD_WETRANSFER = true ] && echo "🔗 WeTransfer" >> release.txt
echo "End of step"
```

同样情况的命令还有 diff，也是经常返回1表示不同，最近碰到了所以知道。

**Comment by admin6750217** [comment]
我的意思没更新的时候一切正常，今天同步更新了一下，编译了一下，编译跑完后就在上传到release，这最后一点就出现了错误，退出！

**Comment by admin6750217** [comment]
QQ截图20210720133326

**Comment by EnnawYang** [comment]
因为false不等于true所以返回了非0的结果导致这步失败了，因为我用不到COWTRANSFER和WETRANSFER所以直接把这俩删了，所以没发现这个问题，可以先向上面那样改下使用，只要不把判断放在最后一行就可以了

**Comment by admin6750217** [comment]
> ・圆的圆的花边花香花香菜花香菜的花销花香菜花香菜花香精的花香花香衣罚花边的花销花香衣架上一副"金币"的"花边"的"花边"的"花销""圆圆"圆圆"机

已解决

**Pull request merged**
